[package]
name = "axum-app"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
sea-orm = { version = "2.0.0-rc.41", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "2.0.0-rc.41", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dependencies]
axum = "0.8.9"
migration = { path = "migration" }
entities = { path = "entities"}
serde = { workspace = true }
tokio = { version = "1.52.3", features = ["full"] }
serde_repr = "0.1.20"
tracing = { workspace = true}
tracing-subscriber = { workspace = true}

[workspace]
members = [
    ".",
    "entities",
    "migration"
]
