[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
sea-orm = { version = "2.0.0-rc.41", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "2.0.0-rc.41", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1.0.228", features = ["derive"] }

[dependencies]
axum = "0.8.9"
migration = { path = "migration" }
entities = { path = "entities"}
serde = { workspace = true }
tokio = { version = "1.52.3", features = ["full"] }
serde_repr = "0.1.20"

[workspace]
members = [
    ".",
    "entities",          # Ваше текущее основное приложение (src)
    "migration"   # Созданный пакет миграций
]
