[package]
name = "axum-app"
version = "0.1.0"
edition = "2021"
default-run = "axum-app"

[workspace.dependencies]
sea-orm = { version = "2", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls"] }
sea-orm-migration = { version = "2", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies]
axum = "0.8"
migration = { path = "migration" }
entities = { path = "entities"}
serde = { workspace = true }
tokio = { workspace = true }
serde_repr = "0.1"
serde_json = "1"
tracing = { workspace = true }
tracing-subscriber = { workspace = true}
sea-orm = { workspace = true, }
sea-orm-migration = { workspace = true, }
validator = { version = "0.21", features = ["derive"] }
utoipa = { version = "5", features = ["axum_extras", "repr"] }
utoipa-swagger-ui = { version = "9", features = ["axum", "debug-embed"] }
tower-http = { version = "0.7", features = ["cors", "trace"] }

[dev-dependencies]
serial_test = "4"

[workspace]
members = [
    ".",
    "entities",
    "migration"
]
