version: '3.8'

services:
  app:
    image: app:latest
    container_name: app
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - 8080:${SERVER_PORT}
    healthcheck:
      test: ["CMD", "./entrypoint.sh", "healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

  postgres:
    image: postgres:18
    container_name: pgsql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge
