FROM rust:1.96-trixie AS build

WORKDIR /app
COPY . .
RUN cargo clean && cargo build

FROM debian:trixie-slim

RUN apt update && apt install -y ca-certificates curl tzdata && rm -rf /var/lib/apt/lists/*
COPY --from=build /app/target/debug/axum-app /usr/local/
CMD ["/usr/local/axum-app"]
